# Generated by Django 3.2.13 on 2022-06-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Infinitive', models.CharField(max_length=30)),
                ('lang', models.CharField(default='fr', max_length=2)),
            ],
        ),
    ]
