# Generated by Django 3.2.13 on 2022-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='group',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='verb',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
